http:
  port: 80

server:
  port: 443
  ssl:
    key-store: classpath:10013290_www.gaoyuanwang.top.pfx
    key-store-password: 21g6np8i
    key-store-type: PKCS12

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB